import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { spaces } from "../../src/host-data";
import { AppIcon, InfoBanner, MetaRow, PageHeader, PrimaryButton, Screen, SectionTitle } from "../../src/ui";
import { colors, type } from "../../src/theme";

export default function HostSpaceDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const space = spaces.find((item) => item.id === id) ?? spaces[0]; return <Screen><PageHeader title={space.name} eyebrow="Hireable space" right={<Pressable style={styles.edit}><AppIcon name="pencil-outline" /></Pressable>} /><Image source={space.image} style={styles.hero} /><View style={styles.intro}><Text style={type.h2}>{space.summary}</Text><Text style={styles.price}>{space.price}</Text></View><View style={styles.metrics}><Metric value={space.area} label="Floor area" /><Metric value={`${space.standing}`} label="Standing" /><Metric value={`${space.seated}`} label="Seated" /></View><View style={styles.meta}><MetaRow icon="accessibility-outline">{space.access}</MetaRow><MetaRow icon="location-outline">First floor · The Island</MetaRow><MetaRow icon="time-outline">Minimum booking: 2 hours</MetaRow></View><SectionTitle title="What’s included" /><View style={styles.features}>{space.features.map((feature) => <View key={feature} style={styles.feature}><AppIcon name="checkmark" size={16} color={colors.pink} /><Text style={styles.featureText}>{feature}</Text></View>)}</View><SectionTitle title="Hire notes" /><InfoBanner icon="information-circle-outline" title="Before accepting a request" body="Allow at least 30 minutes between bookings. Amplified events after 22:00 need venue manager approval." tone="soft" /><View style={styles.actions}><PrimaryButton label="Manage availability" onPress={() => router.push("/(host)/calendar")} /><Pressable style={styles.secondary}><Text style={styles.secondaryText}>Edit space information</Text><AppIcon name="pencil-outline" /></Pressable></View></Screen>; }
function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ edit: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.ink }, hero: { width: "100%", height: 250, backgroundColor: colors.soft }, intro: { padding: 20, gap: 9 }, price: { color: colors.pink, fontSize: 16, fontWeight: "900" }, metrics: { marginHorizontal: 20, flexDirection: "row" }, metric: { flex: 1, minHeight: 88, padding: 10, justifyContent: "space-between", backgroundColor: colors.yellow, borderWidth: 1, borderColor: colors.ink }, metricValue: { fontSize: 21, fontWeight: "900" }, metricLabel: { fontSize: 10, fontWeight: "800" }, meta: { padding: 20, gap: 3 }, features: { marginHorizontal: 20, flexDirection: "row", flexWrap: "wrap", borderTopWidth: 1, borderColor: colors.ink }, feature: { width: "50%", minHeight: 48, flexDirection: "row", alignItems: "center", gap: 7, borderBottomWidth: 1, borderColor: colors.ink }, featureText: { flex: 1, fontSize: 12, fontWeight: "700" }, actions: { padding: 20, gap: 10 }, secondary: { minHeight: 50, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1.5, borderColor: colors.ink }, secondaryText: { fontSize: 15, fontWeight: "800" } });
