import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { hireRequests, spaces, type HireRequest } from "../../src/host-data";
import { StatusBadge } from "../../src/host-ui";
import { AppIcon, InfoBanner, PageHeader, PrimaryButton, Screen, SectionTitle } from "../../src/ui";
import { colors, type } from "../../src/theme";

export default function HireRequestScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const request = hireRequests.find((item) => item.id === id) ?? hireRequests[0]; const [status, setStatus] = useState<HireRequest["status"]>(request.status); const space = spaces.find((item) => item.name === request.space);
  const update = (next: HireRequest["status"]) => setStatus(next);
  return <Screen><PageHeader title="Hire request" eyebrow={request.id} right={<StatusBadge status={status} />} /><View style={styles.hero}><Text style={styles.type}>{request.eventType.toUpperCase()}</Text><Text style={type.h1}>{request.eventName}</Text><Text style={styles.organiser}>Requested by {request.organiser}</Text></View>{status !== request.status ? <InfoBanner icon="checkmark-circle-outline" title={`Request marked ${status.toLowerCase()}`} body="This static prototype updates the page locally; no message has been sent." tone="pink" /> : null}<View style={styles.details}><Detail icon="calendar-outline" label="Date" value={request.date} /><Detail icon="time-outline" label="Hire time" value={request.time} /><Detail icon="location-outline" label="Space" value={request.space} /><Detail icon="people-outline" label="Expected guests" value={`${request.guests} people`} /></View><SectionTitle title="Organiser note" /><View style={styles.note}><Text style={styles.noteText}>{request.note}</Text></View><SectionTitle title="Space check" /><Pressable style={styles.space} onPress={() => space && router.push(`/host-space/${space.id}`)}><View><Text style={styles.type}>REQUESTED SPACE</Text><Text style={type.h3}>{request.space}</Text><Text style={styles.spaceMeta}>{space?.area} · up to {space?.standing} standing</Text></View><AppIcon name="chevron-forward" color={colors.pink} /></Pressable><InfoBanner icon="calendar-outline" title="Calendar conflict check" body="No conflicting booking found. Setup buffer begins 45 minutes before this hire." tone="yellow" /><View style={styles.actions}><PrimaryButton label={status === "Accepted" ? "Accepted" : "Accept request"} icon="checkmark-circle-outline" disabled={status === "Accepted"} onPress={() => update("Accepted")} /><Pressable style={styles.change} onPress={() => update("Changes requested")}><Text style={styles.changeText}>Request changes</Text><AppIcon name="refresh-outline" /></Pressable><Pressable style={styles.decline} onPress={() => update("Declined")}><Text style={styles.declineText}>Decline request</Text></Pressable></View></Screen>;
}
function Detail({ icon, label, value }: { icon: "calendar-outline" | "time-outline" | "location-outline" | "people-outline"; label: string; value: string }) { return <View style={styles.detail}><View style={styles.detailIcon}><AppIcon name={icon} size={20} /></View><View><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ hero: { marginHorizontal: 20, paddingVertical: 20, borderTopWidth: 2, borderBottomWidth: 2, borderColor: colors.ink }, type: { color: colors.pink, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, organiser: { marginTop: 9, color: colors.muted, fontSize: 14 }, details: { padding: 20, gap: 14 }, detail: { minHeight: 48, flexDirection: "row", alignItems: "center", gap: 12 }, detailIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", backgroundColor: colors.yellow, borderWidth: 1, borderColor: colors.ink }, detailLabel: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase" }, detailValue: { marginTop: 2, fontSize: 15, fontWeight: "800" }, note: { marginHorizontal: 20, padding: 16, backgroundColor: colors.soft, borderLeftWidth: 5, borderLeftColor: colors.pink }, noteText: { fontSize: 14, lineHeight: 21 }, space: { marginHorizontal: 20, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1.5, borderColor: colors.ink }, spaceMeta: { marginTop: 5, color: colors.muted, fontSize: 12 }, actions: { padding: 20, gap: 10 }, change: { minHeight: 50, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1.5, borderColor: colors.ink }, changeText: { fontSize: 15, fontWeight: "800" }, decline: { minHeight: 44, alignItems: "center", justifyContent: "center" }, declineText: { color: colors.danger, fontSize: 14, fontWeight: "800" } });
