import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { HostHeader } from "../../src/host-ui";
import { AppIcon, InfoBanner, Screen } from "../../src/ui";
import { colors, type } from "../../src/theme";

const links = [["Venue team & permissions", "people-outline"], ["Hire settings", "settings-outline"], ["Payout details", "wallet-outline"], ["Help for Venue Hosts", "help-circle-outline"]] as const;
export default function HostProfileScreen() { const router = useRouter(); return <Screen><HostHeader title="Host profile" /><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initials}>MR</Text></View><View style={{ flex: 1 }}><Text style={type.h2}>Maya Roberts</Text><Text style={styles.email}>host@artspace.uk</Text><Text style={styles.role}>VENUE MANAGER</Text></View></View><View style={styles.switcher}><View><Text style={styles.switcherLabel}>ACTIVE VENUE</Text><Text style={type.h3}>The Island</Text><Text style={styles.switcherMeta}>Artspace Lifespace · Bristol</Text></View><AppIcon name="chevron-forward" /></View><InfoBanner icon="checkmark-circle-outline" title="Host access verified" body="You can manage spaces, availability, hire requests and venue team access." tone="pink" /><View style={styles.links}>{links.map(([label, icon]) => <Pressable key={label} style={styles.link}><View style={styles.linkLeft}><AppIcon name={icon} /><Text style={styles.linkText}>{label}</Text></View><AppIcon name="chevron-forward" /></Pressable>)}</View><Pressable style={styles.signOut} onPress={() => router.replace("/welcome")}><Text style={styles.signOutText}>Sign out</Text></Pressable></Screen>; }
const styles = StyleSheet.create({ profile: { padding: 20, flexDirection: "row", alignItems: "center", gap: 14 }, avatar: { width: 62, height: 62, borderRadius: 31, alignItems: "center", justifyContent: "center", backgroundColor: colors.pink, borderWidth: 2, borderColor: colors.ink }, initials: { color: colors.white, fontSize: 20, fontWeight: "900" }, email: { color: colors.muted, marginTop: 3 }, role: { color: colors.pink, marginTop: 5, fontSize: 10, letterSpacing: 0.8, fontWeight: "900" }, switcher: { margin: 20, marginTop: 4, padding: 17, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.yellow, borderWidth: 2, borderColor: colors.ink }, switcherLabel: { color: colors.pink, fontSize: 10, letterSpacing: 1, fontWeight: "900" }, switcherMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, links: { margin: 20, borderTopWidth: 2, borderColor: colors.ink }, link: { minHeight: 62, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderColor: colors.ink }, linkLeft: { flexDirection: "row", alignItems: "center", gap: 12 }, linkText: { fontSize: 15, fontWeight: "700" }, signOut: { margin: 20, minHeight: 52, alignItems: "center", justifyContent: "center", borderWidth: 1.5, borderColor: colors.danger }, signOutText: { color: colors.danger, fontSize: 16, fontWeight: "800" } });
